### ISSUE TITLE
testng fails to run in Eclipse Luna

### ISSUE THREAD

**Issue by simplylewis** [cbeust/testng-eclipse#140]
Attempting to run  a TestNG test from Eclipse results in the following exception being thrown. Using Eclipse Luna, Windows 7, Java 1.8.0_31, testng plugin 6.8.22.2015_05_03_1820.

attempting to run a test fails with the following stack trace.

Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

**Comment by missedone** [comment]
@simplylewis 

how does your project look like? is it a regular java project or a maven based project?

could you try with the latest plugin, but first, please uninstall version 6.8.22.2015_05_03_1820 via "Eclipse menu (or "Help" menu if on windows) -> About Eclipse -> Installation Details -> Select the "TestNG" plugin the "installed software" list view -> click "uninstall..." button.

after that, you can install the latest testng-eclipse plugin via marketplace or update site directly.

thanks

**Comment by simplylewis** [comment]
It is a basic Java project. 

To try and isolate the problem tried the following

1. Downloaded a new copy of Eclipse Luna J2EE
2. Installed TestNG plugin from the market place
3. Tried to run the tests in the existing project, TestNG crashes as before
4. Restarted Eclipse and created a new workspace and project
5. Imported the source files from the old project
6. Tried to run TestNG and it crashes as before

**Comment by missedone** [comment]
good, wanna to double check with you, does your project structure look like screenshot below, (under "TestNG" library, there is only one testng.jar), right?
![figure](https://cdn.pbrd.co/images/ghvdPb6.png)

**Comment by simplylewis** [comment]
Looking in the Eclipse error log I see the following

!ENTRY org.testng.eclipse 1 0 2015-05-06 16:40:41.594
!MESSAGE [TestNGLaunchConfigurationDelegate] Launching:
  Classpath: C:\Apps\eclipse\plugins\org.testng.eclipse_6.8.22.201505060335\lib\testng.jar C:\Users\lewisf\workspace\fsm\bin C:\Apps\eclipse\plugins\org.testng.eclipse_6.8.22.201505060335\lib\testng.jar
  VMArgs:    -ea
  Class:     org.testng.remote.RemoteTestNG
  Args:      -serport 49427 -d C:\Users\lewisf\workspace\fsm\test-output C:\Users\lewisf\AppData\Local\Temp\testng-eclipse-507710767\testng-customsuite.xml
java -ea -classpath C:\Apps\eclipse\plugins\org.testng.eclipse_6.8.22.201505060335\lib\testng.jar:C:\Users\lewisf\workspace\fsm\bin:C:\Apps\eclipse\plugins\org.testng.eclipse_6.8.22.201505060335\lib\testng.jar org.testng.remote.RemoteTestNG -serport 49427 -d C:\Users\lewisf\workspace\fsm\test-output C:\Users\lewisf\AppData\Local\Temp\testng-eclipse-507710767\testng-customsuite.xml

!ENTRY org.testng.eclipse 4 4 2015-05-06 16:40:48.189
!MESSAGE Error
!STACK 0
java.net.SocketTimeoutException: Accept timed out
	at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
	at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
	at java.net.PlainSocketImpl.accept(Unknown Source)
	at java.net.ServerSocket.implAccept(Unknown Source)
	at java.net.ServerSocket.accept(Unknown Source)
	at org.testng.remote.strprotocol.BaseMessageSender.initReceiver(BaseMessageSender.java:128)
	at org.testng.eclipse.ui.TestRunnerViewPart.startTestRunListening(TestRunnerViewPart.java:360)
	at org.testng.eclipse.TestNGPlugin.connectTestRunner(TestNGPlugin.java:213)
	at org.testng.eclipse.TestNGPlugin$2.run(TestNGPlugin.java:201)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4147)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3764)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

Ran the TestNG task in a cmd window and got the following;

C:\Users\lewisf>java -ea -classpath C:\Apps\eclipse\plugins\org.testng.eclipse_6
.8.22.201505060335\lib\testng.jar:C:\Users\lewisf\workspace\fsm\bin:C:\Apps\ecli
pse\plugins\org.testng.eclipse_6.8.22.201505060335\lib\testng.jar org.testng.rem
ote.RemoteTestNG -serport 49427 -d C:\Users\lewisf\workspace\fsm\test-output C:\
Users\lewisf\AppData\Local\Temp\testng-eclipse-507710767\testng-customsuite.xml
Error: Could not find or load main class org.testng.remote.RemoteTestNG

**Comment by simplylewis** [comment]
Looking at this further noticed that the classpath was using ':' rather than ';' as the file separator. Correcting this saw the error reported when run in the cmd window change to one showing that jcommander was not found as shown below.

C:\Users\lewisf>java -ea -classpath C:\Apps\eclipse\plugins\org.testng.eclipse_6
.8.22.201505060335\lib\testng.jar;C:\Users\lewisf\workspace\fsm\bin;C:\Apps\ecli
pse\plugins\org.testng.eclipse_6.8.22.201505060335\lib\testng.jar org.testng.rem
ote.RemoteTestNG -serport 49427 -d C:\Users\lewisf\workspace\fsm\test-output C:\
Users\lewisf\AppData\Local\Temp\testng-eclipse-507710767\testng-customsuite.xml
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/
ParameterException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterExcep
tion
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

Then saw that the tstng.jar file is in the classpath line twice but the jcommander-1.47.jar file is missing. So replaced the second occurance with the jocmmander jaw and on the command line the task starts and no errors are thrown.

C:\Users\lewisf>java -ea -classpath C:\Apps\eclipse\plugins\org.testng.eclipse_6
.8.22.201505060335\lib\testng.jar;C:\Users\lewisf\workspace\fsm\bin;C:\Apps\ecli
pse\plugins\org.testng.eclipse_6.8.22.201505060335\lib\jcommander-1.47.jar org.t
estng.remote.RemoteTestNG -serport 49427 -d C:\Users\lewisf\workspace\fsm\test-o
utput C:\Users\lewisf\AppData\Local\Temp\testng-eclipse-507710767\testng-customs
uite.xml

Looking in taskmanager you see a java process running that corresponds to the task.

**Comment by missedone** [comment]
@simplylewis 
that's really helpful, i can fix it later.
before that, you can simply add jcommander.jar to your project classpath, then run test again
thanks

**Comment by cbeust** [comment]
FYI, I fixed the version problem on Market Place, I'll send a separate email.

The JCommander issue is still pending, but I believe @missedone is working on it(?).

**Comment by missedone** [comment]
yes, i'm working on the jcommander issue, will create PR later

**Comment by simplylewis** [comment]
@cbeust, @missedone 
Thanks for the quick fix, as you say the new version works so long as the jcommander-1.47.jar file is explicitly added to the project build path.

**Comment by akash-tomar** [comment]
I have the `jcommander-1.48.jar` present in my build path and I am still getting this error.
