### ISSUE TITLE
Eclipse hangs while running a TestNGTest

### ISSUE THREAD

**Issue by MateuszStefek** [cbeust/testng-eclipse#141]
GUI freezes when I try to run any testng test.

I tried with fresh Eclipse Luna SR2 and with fresh Eclipse Kepler SR2,
completely empty workspaces with one basic test class.
Tesng plugin is downloaded from eclipse marketplace (Only plugin installed).

I don't have any older version of Testng anywhere. I don't have any breakpoints created.

This issue appeared yesterday when I upgraded my Eclipse plugins. Then I tried to isolate the problem. I reinstaled Eclipse, created fresh workspaces, etc. But still can not get this plugin to work. 

I verified that on 3 machines.

An exception can be found in the log:

java.net.SocketTimeoutException: Accept timed out
	at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:135)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
	at java.net.ServerSocket.implAccept(ServerSocket.java:530)
	at java.net.ServerSocket.accept(ServerSocket.java:498)
	at org.testng.remote.strprotocol.BaseMessageSender.initReceiver(BaseMessageSender.java:128)
	at org.testng.eclipse.ui.TestRunnerViewPart.startTestRunListening(TestRunnerViewPart.java:360)
	at org.testng.eclipse.TestNGPlugin.connectTestRunner(TestNGPlugin.java:213)
	at org.testng.eclipse.TestNGPlugin$2.run(TestNGPlugin.java:201)

Update: After adding jcommander-1.47.jar to the project's classpath the issue seems to go away.

**Comment by missedone** [comment]
PR #142 should fix this as well as put jcommand.jar onto the classpath (and "TestNG Library" as well)

**Comment by MateuszStefek** [comment]
OK. The recent plugin update (TestNG 6.9.4.201505110455) fixes the problem for me.
