### ISSUE TITLE
NoClassDefFoundError TestNGPluginConstants

### ISSUE THREAD

**Issue by katelfox** [cbeust/testng-eclipse#146]
Setting up a brand new dev environment, testng is giving me a NoClassDefFoundError.

Eclipse Version:
Eclipse Java EE IDE for Web Developers.

Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

JDK: 1.8

Error:
!ENTRY org.eclipse.ui 4 0 2015-05-12 10:18:59.733
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class org.testng.eclipse.TestNGPluginConstants
	at org.testng.eclipse.ui.util.ConfigurationHelper.findConfiguration(ConfigurationHelper.java:451)
	at org.testng.eclipse.util.LaunchUtil.createLaunchConfiguration(LaunchUtil.java:649)
	at org.testng.eclipse.util.LaunchUtil.launchTypeBasedConfiguration(LaunchUtil.java:457)
	at org.testng.eclipse.util.LaunchUtil.launchCompilationUnitConfiguration(LaunchUtil.java:399)
	at org.testng.eclipse.launch.TestNGLaunchShortcut.run(TestNGLaunchShortcut.java:189)
	at org.testng.eclipse.launch.TestNGLaunchShortcut.launch(TestNGLaunchShortcut.java:136)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.launch(LaunchShortcutExtension.java:420)
	at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.run(LaunchShortcutAction.java:71)
	at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runWithEvent(LaunchShortcutAction.java:123)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4199)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4042)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3669)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

I tried to uninstall the testng plugin, and reinstall it, but still unable to run testng tests from within eclipse.  (I've used this plugin with eclipse on other machines previously)

Update, I pulled from git, and built the testng.jar into the correct place in the plugin folder.  Now am getting:
java.lang.UnsupportedClassVersionError: org/testng/remote/RemoteTestNG : Unsupported major.minor version 51.0

**Comment by cbeust** [comment]
@missedone Any thoughts? I can't imagine how TestNGPluginConstants could throw a `NoClassDefFound`, it's just private statics, no static initializer.

**Comment by cbeust** [comment]
Well, the only line that could cause this is:

      public static final String MAIN_RUNNER = RemoteTestNG.class.getName();

which would indicate `testng.jar` is not on the runtime classpath.

**Comment by katelfox** [comment]
How can I tell if testng.jar is on the runtime classpath?

**Comment by katelfox** [comment]
I grabbed a fresh copy of eclipse, and a fresh copy of testng and everything started working.

**Comment by JnRouvignac** [comment]
If you consider the issue to be fixed, then please close this issue.
Thanks!

**Comment by katelfox** [comment]
I already closed it yesterday.

**Comment by JnRouvignac** [comment]
Sorry I missed that. I got confused by something. Thanks!
