### ISSUE TITLE
NPE in TestRunnerViewPart

### ISSUE THREAD

**Issue by briandealwis** [cbeust/testng-eclipse#157]
We had a [bug report of an NPE from opening the TestRunnerViewPart](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470442).  The stack trace is below.   The NPE is occurring as newSuiteRunInfo() accesses the m_runHistoryAction before it has been configured.

The problem is that TestRunnerViewPart only initializes m_runHistoryAction in configureToolBar(), which is called from createPartControl().  But this updateResultThread() is called as part of the part's init() method.  init() is called before createPartControl(), and in fact it's entirely possible createPartControl() will never be called at all.

!ENTRY org.eclipse.ui 4 4 2015-06-18 15:16:06.921
!MESSAGE Unable to initialize part
!STACK 0
java.lang.NullPointerException
	at org.testng.eclipse.ui.TestRunnerViewPart.newSuiteRunInfo(TestRunnerViewPart.java:418)
	at org.testng.eclipse.ui.TestRunnerViewPart.updateResultThread(TestRunnerViewPart.java:404)
	at org.testng.eclipse.ui.TestRunnerViewPart.init(TestRunnerViewPart.java:219)
	at org.eclipse.ui.internal.ViewReference.initialize(ViewReference.java:140)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:305)

**Comment by cbeust** [comment]
Thanks, @briandealwis. Do you have repro steps, by any chance?

**Comment by briandealwis** [comment]
Sorry, I don't, and I don't use TestNG myself.  The newSuiteRunInfo() call only seems to happen if watch-results is enabled on the particular project?  Perhaps that defaults to off?
