### ISSUE TITLE
Can't recognize runtime TestNG version

### ISSUE THREAD

**Issue by eugenevd** [cbeust/testng-eclipse#222]
Hi

After a clone and build, when running a testNG test I get in a popup box:

Can't recognize runtime TestNG version

I did 
git clone
scripts/set-version 6.9.11-SNAPSHOT   // I found this in the testng.jar MANIFEST
mvn -e clean package

Then in STS update pointing to local
testng-eclipse/testng-eclipse-update-site/target/site

Installs fine.

Running 
Ubuntu 15.04 64bit
STS 4.5.1 64bit
Java 1.7.0_80

Any ideas what I did wrong?

**Comment by missedone** [comment]
hi @eugenevd 

sounds like you build testng plugin yourself, then installed it on the STS?

what's the project you ran the test?
is it plan Java project or maven based project? could you share a small sample project so that i can reproduce the issue?
thanks

**Comment by eugenevd** [comment]
It turns out my project, which uses ivy for dependencies, had a different testng.jar specified.
I removed that, and added the one from 

./testng-eclipse-plugin/lib/testng.jar

Running the test again, I now get a different error:

Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
	at java.lang.Class.getMethod0(Class.java:2866)
	at java.lang.Class.getMethod(Class.java:1676)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 6 more

I've found this existing issue that might be the same thing:
https://github.com/cbeust/testng-eclipse/issues/140

In the past it was only ever needed to have testng.jar
Would I for versions going forward have to adjust my ivy repo to have testng.jar & jcommander.jar together? Any other jars I might find required in future?

**Comment by missedone** [comment]
hi @eugenevd 

the plugin embedded testng.jar was not a fat jar any more.

in your case, Ivy is the dependency management tool, which i suppose will download all dependencies of testng. so it's recommended to use enable project testng jar to run the test.
to enable it, you can right click on the project -> properties -> TestNG -> check the "Use Project TestNG jar" option. see more: http://testng.org/doc/eclipse.html#eclipse-project-properties

**Comment by missedone** [comment]
for what ever reason, add jcommander is enough for most of case.
some other optional dependencies are bsh-2.0b4, or snakeyaml if you use yml file over xml for test suite definition.
see more detail on maven central: http://search.maven.org/#artifactdetails%7Corg.testng%7Ctestng%7C6.9.10%7Cjar

**Comment by eugenevd** [comment]
@missedone 

Yeah, we found that by _disabling_ the "Use Project TestNG jar" option (there is a global option in the eclipse preferences), it doesn't matter that our test project has testng defined in its ivy.xml

Which I take means it will ignore the testng defined in ivy.xml for the test, and use the newly installed version that I've cloned from github and built locally.

So, either disable the project's - it'll use the installed version
OR
update the ivy repo so that the new testng.jar has jcommander.jar with it

Thanks
