### ISSUE TITLE
SecurityException: Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#263]
```
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
    at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:284)
    at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:238)
    at java.util.jar.JarVerifier.processEntry(JarVerifier.java:273)
    at java.util.jar.JarVerifier.update(JarVerifier.java:228)
    at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
    at java.util.jar.JarFile.getInputStream(JarFile.java:450)
    at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:162)
    at java.net.URL.openStream(URL.java:1045)
    at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:84)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:39)
[ServiceLoaderHelper] More than one working implementation for 'null', we will use the first one
Exception in thread "main" java.lang.NoSuchMethodError: org.testng.internal.Utils.defaultIfStringEmpty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    at org.testng.remote.AbstractRemoteTestNG.setHost(AbstractRemoteTestNG.java:59)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:122)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
```

From: http://stackoverflow.com/q/38064860/4234729

**Comment by cbeust** [comment]
Mmmh, I thought at first maybe there's something wrong with the manifest but the `NoSuchMethodError` is puzzling.

@missedone Any thoughts?

**Comment by missedone** [comment]
It looks like they use an pretty old version of testng, probably 5.x.
Now I added more error detail in commit https://github.com/testng-team/testng-remote/commit/1af83840f7de27041eb2ff74b56bfc0b24dfb4bf to suggest people upgrade their testng.

**Comment by missedone** [comment]
closing this since it's not a bug.
however, the plugin now will show more detail message that suggest people upgrade testng version if current used version is below 6.5.1 (aka. they're using unsupported version).

**Comment by missedone** [comment]
just for the record, link to https://github.com/testng-team/testng-remote/issues/34, now testng plugin support testng full 6.x series.
