### ISSUE TITLE
Problem with TestNG Eclipse plugin version 6.9.11.201604020423

### ISSUE THREAD

**Issue by simplylewis** [cbeust/testng-eclipse#265]
Hi

My dev environment is a Eclipse Mars.2 running on Java 1.8.0_74-b02 64 bit / Windows 7. This morning I upgraded the Eclipse TestNG plugin from version TestNG 6.9.10.201512240000 to TestNG 6.9.11.201604020423. Since then a number of tests that were previously working have started failing with a TestNG org.testng.internal.reflect.MethodMatcherException. An example is given in the stack trace below. 

The common factor in all the failing tests is that there is a Mock (using JMockit) supplied as a parameter to the test method. Even if there is no code in the test method the exception is still thrown. This is illustrated in the code fragment below the stack trace.

FAILED: moveFileFails
org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: moveFileFails([Parameter{index=0, type=com.cgi.rbsfta.IFileMonitor, declaredAnnotations=[@mockit.Mocked(stubOutClassInitialization=false)]}])
Arguments: [(java.lang.String)]
    at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
    at org.testng.internal.Invoker.injectParameters(Invoker.java:1228)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1125)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:778)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
    at org.testng.TestNG.runSuites(TestNG.java:1075)
    at org.testng.TestNG.run(TestNG.java:1047)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

Example code

@Test (dependsOnMethods = { "processFilesFails" }, expectedExceptions = { FtaFatalError.class })
    public void moveFileFails(@Mocked final IFileMonitor mockFileMonitor) throws Exception {
    }

Eclipse configuration.
Eclipse IDE for Java EE Developers       4.5.2.20160218-0600      epp.package.jee            null
  JMockit Eclipse Plug-in            1.0.1     JMockit_Eclipse_Plugin.feature.group      Andrejs Jermakovics
  Subversive Revision Graph (Optional)     3.0.0.I20150529-1700     org.eclipse.team.svn.revision.graph.feature.group  Eclipse.org
  Subversive SVN Connectors      5.0.2.I20151228-1700     org.polarion.eclipse.team.svn.connector.feature.group       Polarion Software
  Subversive SVN Integration for the Mylyn Project (Optional)         3.0.0.I20150529-1700            org.eclipse.team.svn.mylyn.feature.group Eclipse.org
  Subversive SVN JDT Ignore Extensions (Optional)           3.0.0.I20150529-1700            org.eclipse.team.svn.resource.ignore.rules.jdt.feature.group           Eclipse.org
  Subversive SVN Team Provider  3.0.4.I20160131-1700     org.eclipse.team.svn.feature.group           Eclipse.org
  Subversive SVN Team Provider Sources 3.0.4.I20160131-1700     org.eclipse.team.svn.source.feature.group            Eclipse.org
  SVNKit 1.7.14 Implementation (Optional)           5.0.0.I20150529-1700            org.polarion.eclipse.team.svn.connector.svnkit17.feature.group      Polarion Software
  TestNG           6.9.11.201604020423     org.testng.eclipse.feature.group   Cedric Beust
  TestNG M2E Integration (Optional)        6.9.11.201604020423     org.testng.eclipse.maven.feature.feature.group      TestNG Team

**Comment by missedone** [comment]
hi @simplylewis
how do you manage your project dependency, especially the testng jar?
do you use the "TestNG Library" of testng plugin?
if so, the embedded testng version update from 6.9.10 to 6.9.11 (when you update the plugin), could you try add a testng 6.9.10 onto your project (and make sure it's prior to the embedded 'TestNG Library' on the classpath), and run the test again.
let's try to narrow down if it's issue in testng lib or the plugin.
thanks

**Comment by missedone** [comment]
if your project is maven managed, could you run the test via maven command line, e.g. `mvn test`, see if things working?

**Comment by missedone** [comment]
closing now, feel free to reopen it if you still have the issue on latest release.
