### ISSUE TITLE
Error reading configuration file

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#271]
```
Exception in thread "main" java.util.ServiceConfigurationError: org.testng.remote.support.RemoteTestNGFactory: Error reading configuration file
at java.util.ServiceLoader.fail(Unknown Source)
at java.util.ServiceLoader.parse(Unknown Source)
at java.util.ServiceLoader.access$200(Unknown Source)
at java.util.ServiceLoader$LazyIterator.hasNextService(Unknown Source)
at java.util.ServiceLoader$LazyIterator.hasNext(Unknown Source)
at java.util.ServiceLoader$1.hasNext(Unknown Source)
at org.testng.remote.support.ServiceLoaderHelper.getFirst(ServiceLoaderHelper.java:16)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:43)
Caused by: java.io.FileNotFoundException: C:\Users\MyUsername(Das System kann die angegebene Datei nicht finden)
//Translation: Can't find the requested file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(Unknown Source)
at java.util.zip.ZipFile.<init>(Unknown Source)
at java.util.jar.JarFile.<init>(Unknown Source)
at java.util.jar.JarFile.<init>(Unknown Source)
at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
at java.net.URL.openStream(Unknown Source)
... 7 more
```

From http://stackoverflow.com/q/38780227/4234729

**Comment by missedone** [comment]
looks like it's encoding issue of the file path: http://stackoverflow.com/questions/38780227/cant-launch-simple-test-with-testng-error-reading-configuration-file#comment64943932_38780227

**Comment by RahulMTechnocredits** [comment]
even i am getting the same errror:

[RemoteTestNG] detected TestNG version 6.14.3
java.util.ServiceConfigurationError: org.testng.xml.ISuiteParser: Error reading configuration file
	at java.util.ServiceLoader.fail(Unknown Source)
	at java.util.ServiceLoader.parse(Unknown Source)
	at java.util.ServiceLoader.access$200(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.hasNextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.hasNext(Unknown Source)
	at java.util.ServiceLoader$1.hasNext(Unknown Source)
	at org.testng.xml.Parser.<clinit>(Parser.java:38)
	at org.testng.TestNG.parseSuite(TestNG.java:295)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
	at org.testng.TestNG.initializeEverything(TestNG.java:995)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:97)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(Unknown Source)
	at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.util.ServiceLoader.parseLine(Unknown Source)
	... 13 more

**Comment by missedone** [comment]
where did you get the testng 6.14.3 jar? could you have the integrity check on that jar file to make sure the file is not corruption duration downloading.

**Comment by ranga1989** [comment]
[RemoteTestNG] detected TestNG version 7.8.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.util.ServiceConfigurationError: org.testng.xml.ISuiteParser: Error accessing configuration file
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1180)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1213)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.testng.xml.internal.Parser.<clinit>(Parser.java:47)
	at org.testng.TestNG.parseSuite(TestNG.java:330)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:394)
	at org.testng.TestNG.initializeEverything(TestNG.java:1062)
	at org.testng.remote.support.RemoteTestNG7_8.initialize(RemoteTestNG7_8.java:23)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.nio.file.NoSuchFileException: C:\Users\Hey
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
	at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
	at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:191)
	at java.base/sun.net.www.protocol.jar.JarFileFactory.getOrCreate(JarFileFactory.java:91)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:132)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:175)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1172)
	... 13 more
i got this Error, when i try to run in testNG

**Comment by krmahadevan** [comment]
@ranga1989 

> Caused by: java.nio.file.NoSuchFileException: C:\Users\Hey

Does this tell you anything on your file system?

**Comment by ranga1989** [comment]
No

**Comment by ranga1989** [comment]
Unknown lifecycle phase "mvn". You must specify a valid lifecycle phase or
a goal in the format <plugin-prefix>:<goal> this error only show while
running maven project with TestNG framework. Can you help me out to resolve
this issue.


Thanks,

Ranganathan.G

+919894427076

**Comment by krmahadevan** [comment]
@ranga1989 - I am not sure what you are asking for. If you run `mvn clean test` that should run your tests. This seems to be something that is specific to your laptop and so you should look at what might be causing the problem

**Comment by ranga1989** [comment]
Hi,

Can you send your number to explain the problem or could you please call me
9894427076.

Thanks,
Ranganathan.G

**Comment by krmahadevan** [comment]
@ranga1989 - Please take time to collect the details required and share the details here which explains the problem. Phone conversations are unfortunately not an option.

**Comment by ranga1989** [comment]
Hi,

Step1: I have install Eclipse 2023-06 and java 1.8
Step2: Create Maven project and add testNG
Step3: Create a sample program
Step4: Run in TestNG

[image: image.png]

**Comment by krmahadevan** [comment]
@ranga1989 - That does not help at all. You haven't told us what verison of TestNG eclipse plugin you used. You haven't told us what version of TestNG are you using. And because you are replying back to comments via email, I believe your screenshot got stripped off as well.

**Comment by ranga1989** [comment]
Eclipse version is : Version: 2023-06 (4.28.0)

**Comment by ranga1989** [comment]
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.8.0</version>
    <scope>test</scope>
</dependency>

Screenshot updated in previous comment

**Comment by krmahadevan** [comment]
The error in your screenshot is NOT related to TestNG or the eclipse plugin. You would need to fix that issue so that we can proceed further with finding out what is causing your issue. Please comment once you have made progress with getting past the maven error in your eclipse installation. Since we don't have access to your eclipse installation, there's not much we can do to fix that error. You might have to google up for possible fixes
