### ISSUE TITLE
java.lang.SecurityException: class "org.osgi.framework.BundleException"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#279]
java.lang.SecurityException: class "org.osgi.framework.BundleException"'s signer information does not match signer information of other classes in the same package
    at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.informatica.sdk.adapter.utils.impl.OSGiUtilsImpl.osgiInit(OSGiUtilsImpl.java:41)
    at com.informatica.cci.reginfo.impl.AdapterInfoImpl.initEnv(AdapterInfoImpl.java:29)
    at com.informatica.CCI.MGF.test.RuntimeAllExpr.setUpEnv(RuntimeAllExpr.java:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
    at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
    at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
    at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
    at org.testng.TestRunner.beforeRun(TestRunner.java:624)
    at org.testng.TestRunner.run(TestRunner.java:592)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
    at org.testng.TestNG.runSuites(TestNG.java:1104)
    at org.testng.TestNG.run(TestNG.java:1076)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

From https://groups.google.com/d/topic/testng-users/FQkSgp14XV8/discussion

**Comment by rkesh-singh** [comment]
I tried with command line its working fine , i feel with testng there is some issue in eclipse without testng in eclipse my application is running fine.

**Comment by missedone** [comment]
well, according to the error message, it implies that you have two or more classes in the same package with different signature. Usually that means the classes come from different JARs, one of which is signed and the other is unsigned.

could you check the classpath of runtime testng process, to see if any suspicion jars, you can get the launch info by clicking "Window" on top level menu of Eclipse -> Show View -> Error Log. see the log entry with message `[TestNGLaunchConfigurationDelegate] Launching:`, double click it you will get the full classpath.

**Comment by missedone** [comment]
see also: http://stackoverflow.com/a/2877355/4867232,

**Comment by juherr** [comment]
@missedone As I asked on the mailing list, is it possible the mismatch is between eclipse (via testng plugin) and the project dependency (it looks they use OSGI too: `OSGiUtilsImpl.osgiInit`)?

**Comment by rkesh-singh** [comment]
@missedone in launch info many jars are present not able to find out suspicious jars.

**Comment by missedone** [comment]
hi @juherr
TestNG plugin appends only the testng-remote jar to the classpath of runtime testng process, as we can see the error occurred at runtime, so I think this error is not relate to Eclipse itself.

oh, @rkesh-singh , could  you confirm your TestNG eclipse plugin is latest?

**Comment by rkesh-singh** [comment]
Ya I downloaded from eclipse marketplace.

On 27 Aug 2016 19:17, "Nick Tan" <notifications@github.com> wrote:

hi @juherr <https://github.com/juherr>
TestNG plugin appends only the testng-remote jar to the classpath of
runtime testng process, as we can see the error occurred at runtime, so I
think this error is not relate to Eclipse itself.

oh, @rkesh-singh <https://github.com/rkesh-singh> , could you confirm your
TestNG eclipse plugin is latest?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cbeust/testng-eclipse/issues/279#issuecomment-242918201>,
or mute the thread

**Comment by missedone** [comment]
here is a bash script can help detect if any duplicate classes:

(save it as `find_class_in_jars.sh`)
```bash
#!/bin/bash

jarListFile=$1
className=$2

for l in $(cat $jarListFile)
do
  echo "finding in $l"
  if [[ -f $l ]]; then
    jar tvf $l | grep $className
  else
    find $l -type f -name "*$className*" -print
  fi
done
```

usage, paste your classpath into a local file, e.g. naming it `jars.list`, saying we want to check class `BundleException`, you can run command: `bash find_class_in_jars.sh ./jars.list BundleException`

let me know what you find.
thanks

**Comment by rkesh-singh** [comment]
finding in org.eclipse.osgi-3.10.101.jar
  1864 Wed Aug 26 10:16:28 IST 2015 org/osgi/framework/BundleException.class
finding in org.eclipse.osgi-org.eclipse.osgi-3.10.101.jar
  1864 Wed Aug 26 10:16:28 IST 2015 org/osgi/framework/BundleException.class

now what i have todo to resolve this problem ?

**Comment by missedone** [comment]
now you need to identify the right osgi jar, which one is correctly signed, remove the other (aka. incorrect one) out of classpath.

**Comment by rkesh-singh** [comment]
am keeping only one but still its throwing same error

java.lang.SecurityException: class "org.osgi.framework.BundleException"'s
signer information does not match signer information of other classes in
the same package

**Comment by missedone** [comment]
which one did you keep? did you try the other one?

**Comment by rkesh-singh** [comment]
ya i tried both of them by adding ones at a time in classpath .

**Comment by missedone** [comment]
hmm, I have no idea then, everything googled hinted that there must be duplicate classes, [1](http://icedtea.classpath.org/pipermail/thermostat/2012-May/001351.html), [2](https://developer.jboss.org/thread/241718?start=0&tstart=0), etc.

last try, could you hit short-cut `ctrl+shift-t` in you Eclipse, and type `org.osgi.framework.BundleException`, how many copies on the result list?

**Comment by rkesh-singh** [comment]
only one .

**Comment by missedone** [comment]
hi @rkesh-singh 
let's see if the output with the JVM switch can help diagnose the issue:
add `-verbose:class` to JVM arguments before launching testng process in Eclipse

**Comment by rkesh-singh** [comment]
hi @missedone 
could you please tell me, what need to observe with output ?
[issue_279.txt](https://github.com/cbeust/testng-eclipse/files/645212/issue_279.txt)

**Comment by missedone** [comment]
the original exception message is: `java.lang.SecurityException: class "org.osgi.framework.BundleException"'s signer information does not match signer information of other classes in the same package`
with JVM switch `-verbose:class` I hope this can help locate where loaded class `org.osgi.framework.BundleException`, but looks like the attached output file does not contain info for class `BundleException`

**Comment by rkesh-singh** [comment]
is there any way we can disable check for signer information ?

**Comment by missedone** [comment]
i'm not sure how to disable it at the moment, but can help take a look later.
however, before that, could you try with the latest in beta update-site, I just pushed a change could (hopefully) avoid potential class loading issue on osgi version classes
thanks

**Comment by rkesh-singh** [comment]
@missedone Thanks a lot nick, its working man.

**Comment by missedone** [comment]
glad to know, thanks

**Comment by missedone** [comment]
just for the record, fixed by https://github.com/testng-team/testng-remote/commit/c1392b38f48383f871f315c2b1d5a17debd749bd

**Comment by rkesh-singh** [comment]
use http://testng.org/eclipse-beta/ to fetch latest eclipse testng beta versions.
