### ISSUE TITLE
Can't recognize the TestNG version on classpath.

### ISSUE THREAD

**Issue by mkolesnikov** [cbeust/testng-eclipse#285]
### Expected behaviour
Eclipse TestNG plugin should be able to run tests in Maven project

### Actual behaviour
java.lang.IllegalArgumentException: invalid version "DEV": non-numeric "DEV"
	at org.osgi.framework.Version.parseInt(Version.java:170)
	at org.osgi.framework.Version.<init>(Version.java:126)
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:87)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:38)
Caused by: java.lang.NumberFormatException: For input string: "DEV"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.osgi.framework.Version.parseInt(Version.java:168)
	... 3 more
[RemoteTestNG] No TestNG version found on classpath
[RemoteTestNG] file:/C:/Users/kolesnikovm/Programs/eclipse/plugins/org.testng.eclipse_6.9.12.201607091356/lib/testng-remote.jar, file:/C:/Users/kolesnikovm/workspace/csi_portal_uplift/csi-core/target/test-classes/, file:/C:/Users/kolesnikovm/workspace/csi_portal_uplift/csi-core/target/classes/, file:/C:/Users/kolesnikovm/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-context-support/4.3.1.RELEASE/spring-context-support-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-beans/4.3.1.RELEASE/spring-beans-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-context/4.3.1.RELEASE/spring-context-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-expression/4.3.1.RELEASE/spring-expression-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-core/4.3.1.RELEASE/spring-core-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/data/spring-data-commons/1.12.2.RELEASE/spring-data-commons-1.12.2.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/data/spring-data-jpa/1.10.2.RELEASE/spring-data-jpa-1.10.2.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-orm/4.3.1.RELEASE/spring-orm-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-jdbc/4.3.1.RELEASE/spring-jdbc-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-aop/4.3.1.RELEASE/spring-aop-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/openjpa/openjpa/2.4.1/openjpa-2.4.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/net/sourceforge/serp/serp/1.15.1/serp-1.15.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1.1/geronimo-jms_1.1_spec-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/geronimo/specs/geronimo-jta_1.1_spec/1.1.1/geronimo-jta_1.1_spec-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-pool/commons-pool/1.5.4/commons-pool-1.5.4.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/xbean/xbean-asm5-shaded/3.17/xbean-asm5-shaded-3.17.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/geronimo/specs/geronimo-jpa_2.1_spec/1.0-alpha-1/geronimo-jpa_2.1_spec-1.0-alpha-1.jar, file:/C:/Users/kolesnikovm/.m2/repository/net/sf/ehcache/ehcache-openjpa/0.2.0/ehcache-openjpa-0.2.0.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/querydsl/querydsl-jpa/4.1.3/querydsl-jpa-4.1.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/querydsl/querydsl-core/4.1.3/querydsl-core-4.1.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mysema/commons/mysema-commons-lang/0.2.4/mysema-commons-lang-0.2.4.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/querydsl/querydsl-sql/4.1.3/querydsl-sql-4.1.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/servicemix/bundles/org.apache.servicemix.bundles.javax-inject/1_2/org.apache.servicemix.bundles.javax-inject-1_2.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/infradna/tool/bridge-method-annotation/1.13/bridge-method-annotation-1.13.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/querydsl/querydsl-collections/4.1.3/querydsl-collections-4.1.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/querydsl/querydsl-codegen/4.1.3/querydsl-codegen-4.1.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mysema/codegen/codegen/0.6.8/codegen-0.6.8.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/eclipse/jdt/core/compiler/ecj/4.3.1/ecj-4.3.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/reflections/reflections/0.9.9/reflections-0.9.9.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/querydsl/querydsl-apt/4.1.3/querydsl-apt-4.1.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-tx/4.3.1.RELEASE/spring-tx-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/net/sf/ehcache/ehcache/2.8.1/ehcache-2.8.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/hibernate/hibernate-validator/5.2.1.Final/hibernate-validator-5.2.1.Final.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/fasterxml/classmate/1.1.0/classmate-1.1.0.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/aspectj/aspectjrt/1.8.9/aspectjrt-1.8.9.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/commons/commons-email/1.3.3/commons-email-1.3.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/javax/mail/mail/1.4.5/mail-1.4.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/freemarker/freemarker/2.3.24-incubating/freemarker-2.3.24-incubating.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/aspectj/aspectjtools/1.8.9/aspectjtools-1.8.9.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/commons/commons-dbcp2/2.1.1/commons-dbcp2-2.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2-patched.jar, file:/C:/Users/kolesnikovm/.m2/repository/joda-time/joda-time/2.9.3/joda-time-2.9.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/slf4j/jul-to-slf4j/1.7.21/jul-to-slf4j-1.7.21.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar, file:/C:/Users/kolesnikovm/workspace/csi_portal_uplift/csi-test/target/classes/, file:/C:/Users/kolesnikovm/.m2/repository/net/sourceforge/cobertura/cobertura/2.1.1/cobertura-2.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/ow2/asm/asm/5.0.1/asm-5.0.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/ow2/asm/asm-util/5.0.1/asm-util-5.0.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/ow2/asm/asm-analysis/5.0.1/asm-analysis-5.0.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar, file:/C:/Users/kolesnikovm/.m2/repository/jaxen/jaxen/1.1.4/jaxen-1.1.4.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/ant/ant/1.8.3/ant-1.8.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/ant/ant-launcher/1.8.3/ant-launcher-1.8.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/ant/ant-junit/1.8.3/ant-junit-1.8.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/mortbay/jetty/servlet-api-2.5/6.1.14/servlet-api-2.5-6.1.14.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/mortbay/jetty/jetty/6.1.14/jetty-6.1.14.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/mortbay/jetty/jetty-util/6.1.14/jetty-util-6.1.14.jar, file:/C:/Program%20Files/Java/jdk1.8.0_102/lib/tools.jar, file:/C:/Users/kolesnikovm/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar, file:/C:/Users/kolesnikovm/.m2/repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-test/4.3.1.RELEASE/spring-test-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/springframework/spring-instrument/4.3.1.RELEASE/spring-instrument-4.3.1.RELEASE.jar, file:/C:/Users/kolesnikovm/.m2/repository/junit/junit/4.12/junit-4.12.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/testng/testng/6.9.13.4/testng-6.9.13.4.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/powermock/powermock-core/1.6.5/powermock-core-1.6.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/powermock/powermock-api-mockito/1.6.5/powermock-api-mockito-1.6.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/powermock/powermock-api-mockito-common/1.6.5/powermock-api-mockito-common-1.6.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/powermock/powermock-api-support/1.6.5/powermock-api-support-1.6.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.5/powermock-module-junit4-common-1.6.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/powermock/powermock-module-junit4/1.6.5/powermock-module-junit4-1.6.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/powermock/powermock-reflect/1.6.5/powermock-reflect-1.6.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/objenesis/objenesis/2.2/objenesis-2.2.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-all/1.1.1/mockrunner-all-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-core/1.1.1/mockrunner-core-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/jdom/jdom/1.0/jdom-1.0.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/kirkk/jaranalyzer/1.2/jaranalyzer-1.2.jar, file:/C:/Users/kolesnikovm/.m2/repository/bcel/bcel/5.1/bcel-5.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/regexp/regexp/1.2/regexp-1.2.jar, file:/C:/Users/kolesnikovm/.m2/repository/jakarta-regexp/jakarta-regexp/1.4/jakarta-regexp-1.4.jar, file:/C:/Users/kolesnikovm/.m2/repository/ant/ant/1.6.5/ant-1.6.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/nekohtml/nekohtml/0.9.5/nekohtml-0.9.5.jar, file:/C:/Users/kolesnikovm/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar, file:/C:/Users/kolesnikovm/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-jms/1.1.1/mockrunner-jms-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-ejb/1.1.1/mockrunner-ejb-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/mockejb/mockejb/0.6-beta2/mockejb-0.6-beta2.jar, file:/C:/Users/kolesnikovm/.m2/repository/cglib/cglib-full/2.0.2/cglib-full-2.0.2.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-jdbc/1.1.1/mockrunner-jdbc-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-jca/1.1.1/mockrunner-jca-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-servlet/1.1.1/mockrunner-servlet-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/tomcat/servlet-api/6.0.37/servlet-api-6.0.37.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/tomcat/jasper/6.0.37/jasper-6.0.37.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/tomcat/juli/6.0.37/juli-6.0.37.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/tomcat/jsp-api/6.0.37/jsp-api-6.0.37.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/tomcat/catalina/6.0.37/catalina-6.0.37.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/tomcat/annotations-api/6.0.37/annotations-api-6.0.37.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/tomcat/el-api/6.0.37/el-api-6.0.37.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/tomcat/jasper-el/6.0.37/jasper-el-6.0.37.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-tag/1.1.1/mockrunner-tag-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/struts/struts-taglib/1.3.10/struts-taglib-1.3.10.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/struts/struts-core/1.3.10/struts-core-1.3.10.jar, file:/C:/Users/kolesnikovm/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-chain/commons-chain/1.2/commons-chain-1.2.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar, file:/C:/Users/kolesnikovm/.m2/repository/commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/com/mockrunner/mockrunner-struts/1.1.1/mockrunner-struts-1.1.1.jar, file:/C:/Users/kolesnikovm/.m2/repository/org/apache/struts/struts-extras/1.3.10/struts-extras-1.3.10.jar, file:/C:/Users/kolesnikovm/.m2/repository/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.jar, file:/C:/Users/kolesnikovm/.m2/repository/dumbster/dumbster/1.6/dumbster-1.6.jar, 
Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.5.1) on your project.
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:123)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:38)

### Steps to reproduce
1. Create a new maven project
2. Add latest TestNG version 6.9.13.4 in dependencies
3. Install TestNG plugin for Eclipse version 6.9.12.201607091356
4. Create a simple TestNG test class
5. Run in from Eclipse: Right Click -> Run As -> TestNG Test

### Running Configuration
* Plugin Version: 6.9.12.201607091356
* Operating System: Win7 64
* Eclipse Neon 4.6.0 build 20160613-1800

**Comment by mkolesnikov** [comment]
Fixed after updating TestNG to 6.9.13.6
