### ISSUE TITLE
java.lang.AbstractMethodError: 

### ISSUE THREAD

**Issue by Raoin** [cbeust/testng-eclipse#326]
### Plugin Version
6.11.0.201703011520

### Expected behaviour
Run test

### Actual behaviour
Throwing an error

org.testng.remote.support.RemoteTestNG6_10$DelegatingTestRunnerFactory.newTestRunner(Lorg/testng/ISuite;Lorg/testng/xml/XmlTest;Ljava/util/List;)Lorg/testng/TestRunner;
at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:561)
at org.testng.SuiteRunner.init(SuiteRunner.java:156)
at org.testng.SuiteRunner.<init>(SuiteRunner.java:110)
at org.testng.TestNG.createSuiteRunner(TestNG.java:1235)
at org.testng.TestNG.createSuiteRunners(TestNG.java:1222)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1074)
at org.testng.TestNG.run(TestNG.java:999)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

### Any relate message in "Error Log" view
The archive: C:/Users/Saurav/.m2/repository/org/testng/testng/6.11.0.201703011520/testng-6.11.0.201703011520.jar which is referenced by the classpath, does not exist.

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows

**Comment by missedone** [comment]
hi @Raoin, do you have duplicate testng jar on your classpath? 

BTW, this msg doesnot make sense to me:
```
The archive: C:/Users/Saurav/.m2/repository/org/testng/testng/6.11.0.201703011520/testng-6.11.0.201703011520.jar which is referenced by the classpath, does not exist.
```

if you use Maven to manage your java project, then the testng version should be 6.11 in your pom.xml. (6.11.0.201703011520 is the version of TestNG Eclipse Plugin).

**Comment by Raoin** [comment]
Thank you, issue has been resolved.
