### ISSUE TITLE
JNI error while running a program using TestNG

### ISSUE THREAD

**Issue by anmishr** [cbeust/testng-eclipse#332]
### Plugin Version---> Latest Version , 6.11
> Eclipse version:  Neon.3 Release (4.6.3)

### Expected behaviour
TestNG should run without error

### Actual behaviour
I am getting JNI error while running a program using TestNG. and its is throwing following exceptions:
Exception in thread "main" java.lang.NoClassDefFoundError: org/testng/TestNGException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.testng.TestNGException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

I have tried the installing the eclipse Luna version still the same problem. Please suggest.

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
Error Log:
Exception in thread "main" java.lang.NoClassDefFoundError: org/testng/TestNGException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.testng.TestNGException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

### The Dependency Management tool for your project

No Dependency
### Operating System

- [ ] Windows 10
![jnierror](https://cloud.githubusercontent.com/assets/28840297/26284227/056b00dc-3e54-11e7-96bf-b7784c55a1a6.PNG)

**Comment by missedone** [comment]
hi @anmishr , this `java.lang.NoClassDefFoundError: org/testng/TestNGException` looks odd, what's the version of TestNG jar being used?
you can add -verbose:class to JVM arguments before launching testng process in Eclipse, then on the console, you will see from which jar the TestNG classes being loaded. then double check if TestNGException in that jar. 

otherwise, it could be a classloader issue, you might need to share a sample project to re-produce the issue.

**Comment by anmishr** [comment]
Hi Nick,
Thank you for the response.
I could fix problem now. It was the wrong import of TestNG annotation. I
can run the program which was causing problem as of now. I assume this
should work now.

I would contact you once again I find the issue in the same.

Regards,
Anu

**Comment by missedone** [comment]
OK, good, feel free to reopen the ticket if you get the same issue. Thx.

**Comment by rahulramanathan** [comment]
@anmishr I am facing the same issue. Could you please guide on how you fixed it?

**Comment by lucky17166** [comment]
Hi Rahul,
  Go to Maven Repository and download JCommander 1.7 jar file and import it to your project...It works

**Comment by tushaarderle** [comment]
downloaded JCommander 1.7 jar file and import .. it works for me below is the download URL for reference : 
https://mvnrepository.com/artifact/com.beust/jcommander/1.7
