### ISSUE TITLE
always ask for beust.com login which I don't know

### ISSUE THREAD

**Issue by letsflykite** [cbeust/testng-eclipse#334]
### Plugin Version
> 'Eclipse -> About Eclipse -> Installation Details -> Locate the TestNG plugin'

> Or, optional, provide the git revision of plugin: "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")

### Expected behaviour
install without asking login

### Actual behaviour
after I cancel the log in panel,
An error occurred while collecting items to be installed
session context was:(profile=_Users_abc_eclipse_jee-neon_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at: http://dl.bintray.com/testng-team/testng-eclipse-release//updatesites/6.11.0.201703011520/plugins/org.testng.eclipse.maven_6.11.0.201703011520.jar. Login canceled by user.
### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/hsun/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/hsun/.eclipse_keyring

org.eclipse.equinox.p2.repository
Error
Tue May 23 16:45:58 PDT 2017
Authentication failed for http://beust.com/eclipse/updatesites/6.10.0.201612030230.
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/hsun/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/hsun/.eclipse_keyring

org.eclipse.equinox.p2.metadata.repository
Error
Tue May 23 16:45:58 PDT 2017
Unable to read repository at http://beust.com/eclipse/6.10.0.

org.eclipse.equinox.p2.core.ProvisionException: Authentication failed for http://beust.com/eclipse/updatesites/6.10.0.201612030230.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:194)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:66)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:88)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:409)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:201)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:166)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:106)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:122)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:409)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:201)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:117)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:102)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$2.runModal(PreloadingRepositoryHandler.java:83)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
### The Dependency Management tool for your project

- [ x] Maven
- [ ] Gradle
- [ ] Ant
- [ x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [x ] OSX
Neon

**Comment by missedone** [comment]
same as #333,

**Comment by missedone** [comment]
@cbeust , could you take a look at the site: http://beust.com/eclipse

<img width="934" alt="screenshot at may 23 17-31-15" src="https://cloud.githubusercontent.com/assets/555134/26381996/acb9f19c-3fdd-11e7-9edc-69c0c70b89c7.png">

**Comment by missedone** [comment]
@cbeust, looks like something wrong at Bintray...

**Comment by juherr** [comment]
Same issue there: https://stackoverflow.com/q/44147507/4234729

**Comment by shubhamj-cuelogic** [comment]
Facing the same issue

**Comment by ariscruz** [comment]
I was able to install it by putting blank username and password and checking the checkbox 'Save password'. The prompt will still show at least 4-6 times more before it will be installed. You need to restart Eclipse after. Im using Mars

![capture](https://cloud.githubusercontent.com/assets/7379907/26396715/9096b5da-40a6-11e7-975f-88e12353a887.PNG)

**Comment by ann2017** [comment]
Thanks a ton @ariscruz .

The above idea given by you is really good. Guys you all can try the same methodology as suggested.
I too installed TestNG and its working absolutely fine.

**Comment by missedone** [comment]
thanks @ariscruz for the workaround, I'll keep contacting Bintray team to resolve this issue.

**Comment by ariscruz** [comment]
No problem guys. Glad to be able to help :) @all, @missedone, @ann2017

**Comment by shubhamj-cuelogic** [comment]
Thanks a ton @ariscruz 

It works for me 👍

**Comment by cbeust** [comment]
Nick, can we get rid of the dependency on bintray to avoid this kind of
thing in the future?

And please update this issue once you figure out what happened.

Thanks!


-- 
Cédric

**Comment by letsflykite** [comment]
I got it working on my home internet. I think the error is because of firewall

**Comment by missedone** [comment]
the issue was gone, all suddenly just like how it appeared.
so I have no idea what's going on, there must be something happened at Bintray.com side.

as the follow up plan, sure, I think we can make beust.com the main update site (just as it was before), and make Bintray as a backup site.

**Comment by missedone** [comment]
@SukumarSpotline , pls check https://github.com/cbeust/testng-eclipse/issues/511#issuecomment-827179825

**Comment by missedone** [comment]
closing this ticket since it's not relevant anymore once we migrate the update site from bintray to github
