### ISSUE TITLE
 run testng  case failed with eclipse

### ISSUE THREAD

**Issue by Juju-Ong** [cbeust/testng-eclipse#338]
I updated my testng eclipse plugin to the version 6.11.0 , still got the same issue!  I'm new with testNG,so what's wrong with my settings ?

### Plugin Version
6.11.0

### Any relate message in "Error Log" view
Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.0.0) on your project.
at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:118)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:48)

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [ ] OSX

**Comment by Juju-Ong** [comment]
#Eclipse runner fails with 6.9.13 #281

**Comment by missedone** [comment]
@Juju-Ong , could you confirm there's only one TestNG jar on your project classpath? and its version >= 6.0

**Comment by Juju-Ong** [comment]
@missedone  there is a maven dependency of testNG ，version is 6.4.0.  And when I changed my eclipse testNG plugin to 6.9.0， that issue disappeared ！

**Comment by missedone** [comment]
so you were saying TestNG 6.4 does not work on TestNG Eclipse Plugin 6.11.0?
could you also have a try with TestNG 6.11 on TestNG Eclipse Plugin 6.11.0?
thx

**Comment by Juju-Ong** [comment]
@missedone maybe! or testNG 6.11.0 doesn't support  my eclipse , version  is  “Neon.3 Release (4.6.3)”. I'm still trying out.

**Comment by missedone** [comment]
@Juju-Ong , could you install the latest beta plugin from `http://beust.com/eclipse-beta`
then enable debug before running test: navigate to top level menu -> "Run -> Run Configurations..." -> select run configuration -> check on the "Debug" option on the "Test" tab.

scroll to the beginning of the console, see if there any suspicions. thx.

----
my sample output:
```
[RemoteTestNG] failed to get TestNG version from class: java.lang.ClassNotFoundException: org.testng.internal.Version
[RemoteTestNG] now trying to parse the version from pom.properties
[RemoteTestNG] parsing TestNG version at jar:file:/Users/nick/.m2/repository/org/testng/testng/6.4/testng-6.4.jar!/META-INF/maven/org.testng/testng/po
m.properties
[RemoteTestNG] detected TestNG version 6.4.0
```

**Comment by ranjitshaw1986** [comment]
tried with the updated version of testng and it worked
