### ISSUE TITLE
String index out of range: -2

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#348]
From https://stackoverflow.com/q/45332104/4234729

![Issue](https://i.stack.imgur.com/9wGBX.jpg)

**Comment by SontiPatil** [comment]
I am too getting same issue while running Testng .java file. Everything was running all ok, and suddenly it started throwing this error

**Comment by missedone** [comment]
@SontiPatil , Do you see any related stack trace on error log view? (Window -> show view -> error log). That will help locate where throw the index out of bound exception.

**Comment by SontiPatil** [comment]
@missedone , here are the logs. I did everything I could, but still same error. None of the testng classes are getting compiled or run.

java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(Unknown Source)
	at org.testng.reporters.XMLStringBuffer.pop(XMLStringBuffer.java:174)
	at org.testng.eclipse.util.CustomSuite.createContentBuffer(CustomSuite.java:127)
	at org.testng.eclipse.util.CustomSuite.getSuiteBuffer(CustomSuite.java:239)
	at org.testng.eclipse.util.CustomSuite.save(CustomSuite.java:258)
	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.createVMRunner(TestNGLaunchConfigurationDelegate.java:305)
	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launchTypes(TestNGLaunchConfigurationDelegate.java:161)
	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launch(TestNGLaunchConfigurationDelegate.java:91)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by missedone** [comment]
@SontiPatil , could you share the testng suite xml file?
if it's auto generated, you can add break point at any test case method, then run as debug, when hit the breakpoint, look at the console output to get the xml suite file location, something like:
```
[TestNG] Running:
  /private/var/folders/54/wsbhhvxs4v92kc0d9rh6h2zr0000gp/T/testng-eclipse--693480342/testng-customsuite.xml
```
copy paste the content of the xml here, which will help diagnose the issue, thanks.

**Comment by missedone** [comment]
@SontiPatil, what testng eclipse version you use?
Do you use custom suite template file ?

**Comment by SontiPatil** [comment]
Testng version: 6.13
Nope, I am not using custom suite template. Tricky part here is that, I had my old project and package created and when I tried running testng class under same package, it throws me above error.
But if I run same program under different project it executes fine.
There is no difference in version which I use to run both classes. Mine is a very simple program as I am new to selenium. 
@BeforeTest
public void launchBrowser(){
...}
@Test 
public void TC_01(){
...}

There is no .xml file. Instead I run same .java file with Testng

**Comment by missedone** [comment]
Could you share your old project?

**Comment by Nannies** [comment]
I have also started getting same error. My project was running fine few days back. However now I am not able to execute any .java file anymore. Keep getting "String index out of range: -2"

**Comment by missedone** [comment]
@Nannies , could you share more detail logs for diagnose? thx

**Comment by timrsfo** [comment]
I am also getting this when I attempt to run a single Test file or a single method within a file via 

    Run as > TestNG

however, if I create a suite.xml file and select it, followed by  Run as > TestNG Suite  It works ;-)

**Comment by missedone** [comment]
@timrsfo , did you see any relate logs on "Error Logs" viewer?

I need more info to locate where throws this Exception, I can't reproduce at my side...

**Comment by missedone** [comment]
@timrsfo , or could you conduct a reproducible sample project for diagnose this issue?

**Comment by timrsfo** [comment]
@missedone I will have to go take a look, let me get back to you by endof today. I do know I was initially able to run individual tests and class tests and then it stopped. It could be that run suite tests messes up the run individual/class ... I will ck.   What is the log you want me to look at and where can i find it?

**Comment by missedone** [comment]
I want to see any relate log in “Error Log” view: click “window -> show view -> Others -> Error Log”
Thanks

**Comment by timrsfo** [comment]
Ok, I should have looked at this before, its looking for a testng.xml file and I don't have one. Is this an internal one used by the plugin? 
   I seem to remember our internal ant build was picking up this testng.xml file and trying to use it automatically, I probably deleted it so the command line build would work. That would explain why it worked for a while and then stopped working.  Is there a plugin configuration that would allow me to give this a different name/location?


    !ENTRY org.testng.eclipse 4 4 2018-10-22 17:27:46.439
    !MESSAGE Error
    !STACK 1
    org.eclipse.core.runtime.CoreException: Variable references non-existent resource : ${workspace_loc:PDI-HCFWebsiteUITests/testng.xml}
        at org.eclipse.debug.internal.core.variables.WorkspaceResolver.resolveValue(WorkspaceResolver.java:66)
        at org.eclipse.core.internal.variables.DynamicVariable.getValue(DynamicVariable.java:56)
        at org.eclipse.core.internal.variables.StringSubstitutionEngine.resolve(StringSubstitutionEngine.java:269)
        at org.eclipse.core.internal.variables.StringSubstitutionEngine.substitute(StringSubstitutionEngine.java:192)
        at org.eclipse.core.internal.variables.StringSubstitutionEngine.performStringSubstitution(StringSubstitutionEngine.java:87)
        at org.eclipse.core.internal.variables.StringVariableManager.performStringSubstitution(StringVariableManager.java:591)
        at org.eclipse.core.internal.variables.StringVariableManager.performStringSubstitution(StringVariableManager.java:357)
        at org.testng.eclipse.util.CustomSuite.createContentBuffer(CustomSuite.java:111)
        at org.testng.eclipse.util.CustomSuite.getSuiteBuffer(CustomSuite.java:239)
        at org.testng.eclipse.util.CustomSuite.save(CustomSuite.java:258)
        at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.createVMRunner(TestNGLaunchConfigurationDelegate.java:301)
        at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launchTypes(TestNGLaunchConfigurationDelegate.java:157)
        at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launch(TestNGLaunchConfigurationDelegate.java:91)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
        at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
        at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
    !SUBENTRY 1 org.eclipse.core.resources 4 368 2018-10-22 17:27:46.440
    !MESSAGE Variable references non-existent resource : ${workspace_loc:MyWorkSpaceName/testng.xml}

    !ENTRY org.eclipse.core.jobs 4 2 2018-10-22 17:27:46.442
    !MESSAGE An internal error occurred during: "Launching PLDFullDetailViewTests.loadingReportTest".
    !STACK 0
    java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:1931)
        at org.testng.reporters.XMLStringBuffer.pop(XMLStringBuffer.java:174)
        at org.testng.eclipse.util.CustomSuite.createContentBuffer(CustomSuite.java:127)
        at org.testng.eclipse.util.CustomSuite.getSuiteBuffer(CustomSuite.java:239)
        at org.testng.eclipse.util.CustomSuite.save(CustomSuite.java:258)
        at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.createVMRunner(TestNGLaunchConfigurationDelegate.java:301)
        at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launchTypes(TestNGLaunchConfigurationDelegate.java:157)
        at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launch(TestNGLaunchConfigurationDelegate.java:91)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
        at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
        at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by missedone** [comment]
@timrsfo , pls check your settings of "Template XML FIle" either on Eclipse global preference or project properties page.

![image](https://user-images.githubusercontent.com/555134/47336102-2d8a6e80-d643-11e8-86b8-aa817c0f5fdb.png)

**Comment by missedone** [comment]
@timrsfo , i just raised a PR #405, it throws a more human readable exception before "index out of range" exception occurs.

**Comment by missedone** [comment]
@timrsfo , could you verify the beta update site: https://dl.bintray.com/testng-team/testng-eclipse/updatesites/7.0.0.201810231130/

**Comment by timrsfo** [comment]
This is the new "details" error string - much more telling ;-)

    An internal error occurred during: "Launching MyTestClass.someTestMethod".
    Failed to create TestNG suite from "Template XML File" '${workspace_loc:MyProject/testng.xml}':
    Variable references non-existent resource : ${workspace_loc:MyProject/testng.xml}

For me my Project Specific value was set as follows: 

    Given: Template XML File:  ${workspace_loc:MyProject/testng.xml}

Hopefully, this will clear things up for others that encounter this error

Summary:  
you can set up a "TestNG Template xml" file (e.g. testng.xml,  MyCustomTestNGTemplate.xml, etc)
in a directory of your choice. You can use this to set things like parallel, etc. You can have a global one
or a project specific version. 
NOTE: If you have this value set - You MUST have the specified file in the specified location. 
NOTE: You can leave this value UnSet/Clear/Blank,  and you will no longer have an issue

**Comment by missedone** [comment]
Thank you @timrsfo for helping locate the exception and the detail summary
