### ISSUE TITLE
trigger of testng.xml(suite.xml) fails suddenly

### ISSUE THREAD

**Issue by reply2sesh** [cbeust/testng-eclipse#396]
I am unable to trigger testng.xml(suite.xml). This used to work earlier until but suddenly fails to execute. There is no clue anywhere on what the error is. appreciate if some guidance
Suite.xml file attached as text as I was unable to attach xml directly

[suite.txt](https://github.com/cbeust/testng-eclipse/files/2011817/suite.txt)

**### Any relate message in "Error Log" view**

[RemoteTestNG] detected TestNG version 6.11.0
org.testng.TestNGException: 
The test(s) <[${testname}]> cannot be found.
	at org.testng.TestNG.extractTestNames(TestNG.java:435)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:309)
	at org.testng.remote.AbstractRemoteTestNG.initialize(AbstractRemoteTestNG.java:136)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:97)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

### The Dependency Management tool for your project
- [ ] Maven

### Operating System
- [ ] OSX

**Comment by missedone** [comment]
I assume you just updated TestNG Eclipse Plugin to [6.14.0.201802161500](https://github.com/cbeust/testng-eclipse/releases/tag/6.14.0.201802161500), you can disable the feature, navigate to Eclipse Preferences -> TestNG -> Maven -> then uncheck the option "properties (TestNG CLI arguments)

**Comment by missedone** [comment]
closing this now as no feedback for a long time, feel free to re-open it.
