### ISSUE TITLE
Testng-eclipse can not find classes in non exported packages in a java modular maven project

### ISSUE THREAD

**Issue by olovm** [cbeust/testng-eclipse#413]
### Problem Statement
Using a minimal standard java modular maven project with separate src and test folders runs as expected as long as the class beeing tested is in a package that is exported in modular-info.java. If it is not, testng-eclipse can not find the class to test, see error message below. It works as expected if run using maven (Run As / Maven test).
See: https://github.com/olovm/modular2.git for an example project

I can work around the problem by adding the following to the automatically created run config in the Arguments tab, under VM Options:
--add-opens org.example.modular2/org.example.modular2=ALL-UNNAMED
but it needs to be done for every unique test run :(

This is when running on eclipse 201812, latest beta of testng-eclipse and java 11.

### Any relate message in "Error Log" view
[RemoteTestNG] revisions:
	git.commit.id=8139f16
	git.build.version=1.4.0-SNAPSHOT
	git.branch=8139f16eccd87e35f80a8bf2edc32dcad7f1194b
[RemoteTestNG] loaded class org.testng.internal.Version at file:/home/olov/.m2/repository/org/testng/testng/6.14.3/testng-6.14.3.jar
[RemoteTestNG] detected TestNG version 6.14.3
[RemoteTestNG] Invoked with -serport 36573 -protocol json -d /home/olov/workspace/modular2/test-output /tmp/testng-eclipse-1543958007/testng-customsuite.xml 
[BaseMessageSender] Waiting for Eclipse client on localhost:36573
[BaseMessageSender] Received a connection from Eclipse on localhost:36573
[BaseMessageSender] Connection established, starting reader thread
[BaseMessageSender] ReaderThread waiting for an admin message
[JsonMessageSender] Sending message [GenericMessage ==> suiteCount:1, testCount:1]
[BaseMessageSender] ReaderThread received admin message:>ACK
[BaseMessageSender] Admin message:>ACK
[BaseMessageSender] Received ACK:>ACK
[BaseMessageSender] Admin message:>ACK
[BaseMessageSender] Received ACK:>ACK
org.testng.TestNGException: 
Cannot instantiate class org.example.modular2.Modular2Test
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:30)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:423)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
	at org.testng.TestClass.getInstances(TestClass.java:95)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:81)
	at org.testng.TestClass.init(TestClass.java:73)
	at org.testng.TestClass.<init>(TestClass.java:38)
	at org.testng.TestRunner.initMethods(TestRunner.java:389)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:192)
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:713)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public org.example.modular2.Modular2Test() accessible: module org.example.modular2 does not "exports org.example.modular2" to unnamed module @7530ad9c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:189)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:182)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:23)
	... 25 more
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)

### The Dependency Management tool for your project

- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [x] Linux
- [ ] OSX

**Comment by missedone** [comment]
As a workaround you can put the “add-open” to the “argLine” of maven-surefire-plugin configurations

**Comment by olovm** [comment]
That is a much better workaround, thank you!

**Comment by missedone** [comment]
@olovm , could you verify the beta update site: https://dl.bintray.com/testng-team/testng-eclipse/updatesites/7.0.0.201901010437/

**Comment by missedone** [comment]
Thank you @olovm
