### ISSUE TITLE
Eclipse 4.9 'Invalid classpath container: 'TestNG'

### ISSUE THREAD

**Issue by jmetertea** [cbeust/testng-eclipse#422]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**
I'm using Eclipse 4.9, I tried to update new TestNG upgrade(7)

It failed so I rollback to previous version and now I have an issue

'Invalid classpath container: 'TestNG' in project 
I can't fix it by

clean project (maven can't be execute due to NullpointerException below errors)

Reinstall TestNG

Remove and add TestNG library

I didn't find relevant answers for this issue
Eclipse 4.10 doesn't support TestNG plugin 

### Any relate message in "Error Log" view
Error log:

java.lang.NullPointerException
    at org.eclipse.jem.workbench.utility.JavaModelListener.isInClasspath(JavaModelListener.java:367)
    at org.eclipse.jem.workbench.utility.JavaModelListener.isInClasspath(JavaModelListener.java:412)
    at org.eclipse.jem.workbench.utility.JavaModelListener.isInClasspath(JavaModelListener.java:384)
    at org.eclipse.jem.workbench.utility.JavaModelListener.isInClasspath(JavaModelListener.java:305)
    at org.eclipse.jem.internal.adapters.jdom.JavaReflectionSynchronizer.processJavaElementChanged(JavaReflectionSynchronizer.java:117)
    at org.eclipse.jem.workbench.utility.JavaModelListener.processDelta(JavaModelListener.java:116)
    at org.eclipse.jem.internal.adapters.jdom.JavaReflectionSynchronizer.processDelta(JavaReflectionSynchronizer.java:343)
    at org.eclipse.jem.workbench.utility.JavaModelListener.processChildren(JavaModelListener.java:78)
    at org.eclipse.jem.internal.adapters.jdom.JavaReflectionSynchronizer.processChildren(JavaReflectionSynchronizer.java:336)
    at org.eclipse.jem.workbench.utility.JavaModelListener.processJavaElementChanged(JavaModelListener.java:176)
    at org.eclipse.jem.workbench.utility.JavaModelListener.processDelta(JavaModelListener.java:113)
    at org.eclipse.jem.internal.adapters.jdom.JavaReflectionSynchronizer.processDelta(JavaReflectionSynchronizer.java:343)
    at org.eclipse.jem.workbench.utility.JavaModelListener.elementChanged(JavaModelListener.java:63)
    at org.eclipse.jem.internal.adapters.jdom.JavaReflectionSynchronizer.elementChanged(JavaReflectionSynchronizer.java:265)
    at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1738)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    at org.eclipse.jdt.internal.core.DeltaProcessor.notifyListeners(DeltaProcessor.java:1726)
    at org.eclipse.jdt.internal.core.DeltaProcessor.firePostChangeDelta(DeltaProcessor.java:1559)
    at org.eclipse.jdt.internal.core.DeltaProcessor.fire(DeltaProcessor.java:1535)
    at org.eclipse.jdt.internal.core.DeltaProcessor.notifyAndFire(DeltaProcessor.java:2256)
    at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2146)
    at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:477)
    at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:290)
    at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:153)
    at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:379)
    at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:160)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### The Dependency Management tool for your project

- [X ] Maven
- [ ] Gradle
- [ ] Ant
- [X ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [X ] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
@jmetertea , have you tried the latest release 6.14.3.201902250526:
https://github.com/cbeust/testng-eclipse#update-sites

**Comment by Jochen76** [comment]
Same issue here: Invalid classpath container: 'TestNG' in project '...'

But I am using Eclipse 2018-12 (4.10.0). 
As plugin I am using org.testng.eclipse_7.0.0.201903221544.jar / testng-7.0.0-beta3.jar.

**Comment by missedone** [comment]
closing this since no reply from OP
