### ISSUE TITLE
TestNG Error

### ISSUE THREAD

**Issue by Pradheepviki** [cbeust/testng-eclipse#484]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

[RemoteTestNG] detected TestNG version 7.0.1
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

### The Dependency Management tool for your project

- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows

**Comment by missedone** [comment]
closing this as duplicates with #472 .

see solution: https://github.com/cbeust/testng-eclipse/issues/472#issuecomment-599251156
