### ISSUE TITLE
Getting NoClassDefFoundError exception when working with Testng and excel workbook 

### ISSUE THREAD

**Issue by sravanthi1047** [cbeust/testng-eclipse#499]
Hi, 
I am very new bie to testng and selenium. While learning, iam trying to read text from workbook and google the same. Through a normal script its running with no issues at all. But the same code in terms of testng framework raising NoClassDefFoundError while accessing the workbook. Please help me with this. 

Below is the code that is running fine:

public static void main(String[] args){
ExcelUtil xl= new ExcelUtil("<xl file path>", "<sheet name>");

public ExcelUtil(String xlFilePath) throws IOException {
		// TODO Auto-generated constructor stub
		File xlFile= new File(xlFilePath);
		InputStream fIn= new FileInputStream(xlFile);
		if (!xlFile.exists())
			wb= XSSFWorkbookFactory.createWorkbook();
		else
			wb = new XSSFWorkbook(fIn);    ------> throwing NoClassDeffound error    
}
		
But, the same piece of code of ExcelUtil when called from @test annotated test method, is throwing the following error
[Utils] [ERROR] [Error] java.lang.NoClassDefFoundError: org/apache/commons/collections4/ListValuedMap
	at GlobalUtil.ExcelUtil.&lt;init&gt;(ExcelUtil.java:39)
	at testNgPractise.Google.GetSignupData(Google.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:79)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:48)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:148)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:788)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:588)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
	at org.testng.TestNG.runSuites(TestNG.java:1066)
	at org.testng.TestNG.run(TestNG.java:1034)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections4.ListValuedMap
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 34 more

### The Dependency Management tool for your project

-[ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows

Thanks
Sravanthi

**Comment by missedone** [comment]
@sravanthi1047 , i think you're missing some dependencies.
BTW, you may ask such question on stackoverflow

**Comment by sandeepnegi1996** [comment]
Hi @sravanthi1047 

Its great that you have share your thoughts,

But I have some doubts regarding your problem,

While using Testng if you are using maven to manage your dependencies like for the workbook you need some dependency like apache-poi and others,

So, If can share your pom.xml file which contains all the list of dependency we will be able to help you out.

**Keep coding Keep Learning**

**Comment by sravanthi1047** [comment]
Hi Sandeep,  
I am not using maven here. Just the plain script involving testng class and Apache utility methods. 
Please guide. Thanks

**Comment by sandeepnegi1996** [comment]
Hi @sravanthi1047 

so while using testng there are several things you need to keep in mind

1. Install the testng plugin in your eclipse but I have tried with so many eclipse but they doesn't support testng plugin so I started using Eclipse photon for that, You can install testng plugin in your eclipse

2. As you have mentioned that you are not using maven, But I would recommend you to use maven since maven is just a dependency and build tool, So what it does it will automatically download the jar file required for your project, you don't need to add the jar files manually. 

3. After doing the second step you can install the right dependency as well as a dependency for testng, Now you can try to run the same program using testng.xml, Inside testng.xml you need to add the classes that you want to run, as soon as you will run the testng.xml it will run all the cases as well as generate the report, 

Feel free to post more such queries, I know my solution is more generic but it will help you out in long run, If you need code samples let me know.

**Keep Coding Keep Learning**
