### ISSUE TITLE
SSL Peer Unverified Error when trying to install Eclipse Plugin

### ISSUE THREAD

**Issue by rvesse** [cbeust/testng-eclipse#526]
### Problem Statement

When trying to install/update the plugin from the new update site (since Bintary has been shutdown) the update fails with the following error:

![Screenshot 2021-06-15 at 10 42 13](https://user-images.githubusercontent.com/2104864/122032143-45502b80-cdc7-11eb-9a88-192a183ca65a.png)

This can reproduced both when using the Eclipse Marketplace approach to installation and when manually adding the update site

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

Bunch of similar error messages from multiple attempts at this:

![Screenshot 2021-06-15 at 10 49 45](https://user-images.githubusercontent.com/2104864/122032335-729cd980-cdc7-11eb-900a-d8f419dd197f.png)

Detailed stack trace from one example:

```
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <testng.org> doesn't match any of the subject alternative names: [www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:507)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:437)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:248)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### The Dependency Management tool for your project

- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [x] OSX

**Comment by sivapeddareddigari** [comment]
I am facing the same error on Windows 10 machine. 
![Capture617](https://user-images.githubusercontent.com/10032568/122485382-ba2c8c80-cfa4-11eb-8e3c-09268b41302f.PNG)

**Comment by vishalbiradar** [comment]
Even I am facing the same issue.
Tried with Eclipse Market place and as well as Install New Software wizards in eclipse.
Can anyone please help us resolve this issue?

**Comment by missedone** [comment]
let's track on #529
