### ISSUE TITLE
Winappriver, TestNG is not working.

### ISSUE THREAD

**Issue by YeonwooJeong** [cbeust/testng-eclipse#535]
### Problem Statement
Winappriver, TestNG is not working. what's problem??
We are attempting to operate the test that was normally operated by junit as TestNG. 

### Any relate message in "Error Log" view

https://user-images.githubusercontent.com/8816386/173591875-a5df49b7-9163-4150-9f27-d1b345cad6d0.mp4

![image](https://user-images.githubusercontent.com/8816386/173591831-3e519138-8339-48a4-96c6-e1131d7ed69f.png)

![image](https://user-images.githubusercontent.com/8816386/173594967-7ea74949-eda7-445a-a4e7-91025a0d39c6.png)

![image](https://user-images.githubusercontent.com/8816386/173595004-b943c115-5d36-490c-9915-98bd6a548f98.png)

java.util.concurrent.CancellationException
	at org.eclipse.jface.internal.text.codemining.CancellationExceptionMonitor.isCanceled(CancellationExceptionMonitor.java:33)
	at org.testng.eclipse.ui.codemining.TestCodeMiningProvider.processElements(TestCodeMiningProvider.java:80)
	at org.testng.eclipse.ui.codemining.TestCodeMiningProvider.processElements(TestCodeMiningProvider.java:89)
	at org.testng.eclipse.ui.codemining.TestCodeMiningProvider.mineForTests(TestCodeMiningProvider.java:67)
	at org.testng.eclipse.ui.codemining.TestCodeMiningProvider.lambda$0(TestCodeMiningProvider.java:40)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

### The Dependency Management tool for your project

- [ v ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [v] Windows

**Comment by YeonwooJeong** [comment]
This issue was solved by deleting the project and receiving it again and installing TestNG again.
