### ISSUE TITLE
run using testNG issue: java.lang.NoClassDefFoundError: org.testng.internal.ClassImpl 

### ISSUE THREAD

**Issue by ShariHaridas** [cbeust/testng-eclipse#78]
Please help me... When I run my test suite I am getting this error.. I tried all ways listed under 
http://code.google.com/p/testng-eclipse/issues/detail?id=43 and nothing worked for me..:( I am not using maven.

java.lang.NoClassDefFoundError: org.testng.internal.ClassImpl
   at java.lang.Class.initializeClass(libgcj.so.90)
   at org.testng.internal.BaseClassFinder.findOrCreateIClass(BaseClassFinder.java:48)
   at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:117)
   at org.testng.TestRunner.initMethods(TestRunner.java:413)
   at org.testng.TestRunner.init(TestRunner.java:235)
   at org.testng.TestRunner.init(TestRunner.java:205)
   at org.testng.TestRunner.<init>(TestRunner.java:160)
   at org.testng.remote.RemoteTestNG$1.newTestRunner(RemoteTestNG.java:142)
   at org.testng.remote.RemoteTestNG$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG.java:271)
   at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:561)
   at org.testng.SuiteRunner.init(SuiteRunner.java:157)
   at org.testng.SuiteRunner.<init>(SuiteRunner.java:111)
   at org.testng.TestNG.createSuiteRunner(TestNG.java:1278)
   at org.testng.TestNG.createSuiteRunners(TestNG.java:1265)
   at org.testng.TestNG.runSuitesLocally(TestNG.java:1119)
   at org.testng.TestNG.run(TestNG.java:1036)
   at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
   at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
   at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ClassNotFoundException: com.google.inject.Module not found in gnu.gcj.runtime.SystemClassLoader{urls=[file:/afs/.cpiv.com/techhome/shari.dh/.eclipse/org.eclipse.platform_3.5.0_2045279800/plugins/org.testng.eclipse_6.8.0.20121120_1820/lib/testng.jar,file:/afs/.cpiv.com/techhome/shari.dh/workspace/nstest/bin/,file:/afs/.cpiv.com/techhome/shari.dh/Desktop/selenium-server-standalone-2.28.0.jar,file:/afs/.cpiv.com/techhome/shari.dh/Desktop/selenium-java-2.28.0.zip,file:/afs/.cpiv.com/techhome/shari.dh/Desktop/org.testng.eclipse_6.8.0.20121120_1820.jar], parent=gnu.gcj.runtime.ExtensionClassLoader{urls=[], parent=null}}
   at java.net.URLClassLoader.findClass(libgcj.so.90)
   at gnu.gcj.runtime.SystemClassLoader.findClass(libgcj.so.90)
   at java.lang.ClassLoader.loadClass(libgcj.so.90)
   at java.lang.ClassLoader.loadClass(libgcj.so.90)
   at java.lang.Class.initializeClass(libgcj.so.90)
   ...18 more

Thanks!

**Comment by missedone** [comment]
closing now, if the issue still on the recent version, create a new ticket then.
